runOnDraft: false
# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
- wip

# Set to true to add reviewers to pull requests
addReviewers: true
# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1
useReviewGroups: true
reviewGroups:
  owners:
  - posquit0
  maintainers:
  - posquit0

# true: Add assignees to pull requests
# 'author': Set the PR creator as the assignee.
addAssignees: 'author'
# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
# numberOfAssignees: 2
useAssigneeGroups: false
# assigneeGroups:
#   groupA:
#   - assigneeA
#   - assigneeB
#   - assigneeC
#   groupB:
#   - assigneeD
#   - assigneeE
#   - assigneeF
