version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/account"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/iam-group"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/iam-role"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/iam-user"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/org-account"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/org-organization"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/org-organizational-unit"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/service-quota-requests"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/sso-account-assignment"
  schedule:
    interval: "daily"
- package-ecosystem: "terraform"
  directory: "/modules/sso-permission-set"
  schedule:
    interval: "daily"
