# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to account module."
  name: ":floppy_disk: account"
- color: "fbca04"
  description: "This issue or pull request is related to iam-group module."
  name: ":floppy_disk: iam-group"
- color: "fbca04"
  description: "This issue or pull request is related to iam-oidc-identity-provider module."
  name: ":floppy_disk: iam-oidc-identity-provider"
- color: "fbca04"
  description: "This issue or pull request is related to iam-policy module."
  name: ":floppy_disk: iam-policy"
- color: "fbca04"
  description: "This issue or pull request is related to iam-predefined-policies module."
  name: ":floppy_disk: iam-predefined-policies"
- color: "fbca04"
  description: "This issue or pull request is related to iam-role module."
  name: ":floppy_disk: iam-role"
- color: "fbca04"
  description: "This issue or pull request is related to iam-saml-identity-provider module."
  name: ":floppy_disk: iam-saml-identity-provider"
- color: "fbca04"
  description: "This issue or pull request is related to iam-user module."
  name: ":floppy_disk: iam-user"
- color: "fbca04"
  description: "This issue or pull request is related to region module."
  name: ":floppy_disk: region"
