# Warning
- color: "ee0701"
  description: "Categorize to note any change that requires extra attention."
  name: ":warning: breaking change"
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Task Types
- color: "1d76db"
  description: "Improvements or additions to documentation."
  name: ":pencil2: documentation"
- color: "1d76db"
  description: "A new feature of the project."
  name: ":pencil2: feature"
- color: "1d76db"
  description: "Any dependency updates, housekeeping, or maintenance work."
  name: ":pencil2: maintenance"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This issue or pull request is invalid."
  name: ":pray: invalid"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"