repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
  - id: terraform_fmt
    args:
    - --args=-diff
  - id: terraform_validate
    args:
    - --hook-config=--retry-once-with-cleanup=true
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    files: ^modules/
  - id: terraform_docs
    args: ["--args=--sort-by required"]
- repo: https://github.com/adrienverge/yamllint
  rev: v1.29.0
  hooks:
  - id: yamllint
