name: Sync GitHub labels

on:
  push:
    branches:
    - main
    paths:
    - ".github/labels.yaml"

jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - uses: micnncim/action-label-syncer@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        manifest: ".github/labels.yaml"
