name: Integration - Terraform


on:
  push:
    branches:
    - main

  pull_request: {}


concurrency:
  group: integration-terraform-${{ github.ref }}
  cancel-in-progress: true


jobs:
  terraform:
    name: Terraform
    uses: tedilabs/github-actions/.github/workflows/terraform.modules.integration.yaml@main

    with:
      paths: |
        modules/**
        examples/**
      paths_max_depth: "2"

      terraform_version: latest
      terraform_host: app.terraform.io

      fmt_enabled: true

      validate_enabled: true

      tflint_enabled: true
      tflint_version: latest
      tflint_config_file: .tflint.hcl
      tflint_minimum_failure_severity: warning

      terraform_docs_enabled: true
      terraform_docs_version: latest
      terraform_docs_config_file: .terraform-docs.yml

    secrets:
      terraform_token: ${{ secrets.TERRAFORM_TOKEN }}
