name: Welcome for First Issue or Pull Request

on:
- pull_request
- issues

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Welcome for First Issue or Pull Request
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thank you very much for your first issue to this project. It is much appreciated.
        pr-message: |
          Thank you very much for your first pull request to this project. It is much appreciated.
